# -*- coding: utf-8 -*-
"""Task3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sOqlP0xzcdFpQRoOU5GD4fhHSl3BPuFv
"""

#Downloading version 2.16.1 of datasets for the access of conll2023, since updated version not has the dataset
!pip install datasets==3.6.0

#Loading the dataset
from datasets import load_dataset
dataset = load_dataset("conll2003")

train = dataset["train"]
val = dataset["validation"]
test = dataset["test"]

print(train)

print(val)

print(test)

print(train[0]) #printing first sentence or the first word in the dataset

## Decoding the first row for the better understanding
example = train[0]

pos_names   = train.features["pos_tags"].feature.names
chunk_names = train.features["chunk_tags"].feature.names
ner_names   = train.features["ner_tags"].feature.names

for t, p, c, n in zip(
    example["tokens"],
    example["pos_tags"],
    example["chunk_tags"],
    example["ner_tags"]
):
    print(f"{t:10}  POS={pos_names[p]}  CHUNK={chunk_names[c]}  NER={ner_names[n]}")

#Separating the inputs and the outputs
X_train, y_train = train["tokens"], train["ner_tags"]
X_val, y_val = val["tokens"], val["ner_tags"]
X_test, y_test = test["tokens"], test["ner_tags"]

print(len(X_train), len(X_val), len(X_test))

!pip install sklearn-crfsuite

# Creating a Feature matrix for each word in a particular sentence
def features(sentence, i):
    current_word = sent[i]
    # Find the features of for the current word
    features = {
        "bias": 1.0, #Bias
        "word.lower()": current_word.lower(), # the word with all small letters
        "word[-3:]": current_word[-3:], #Last three letters of the word
        "word[-2:]": current_word[-2:], #Last two letters of the word
        "word[:2]": current_word[:2], # First two letters of the word
        "word[:3]": current_word[:3], # First three letters of the word
        "word.isupper()": current_word.isupper(), #All the elements in the word are captial or not
        "word.istitle()": current_word.istitle(),#Is the word is title
        "word.isdigit()": current_word.isdigit(),# Is it a number
    }

    if i > 0:
        prev_word = sentence[i-1]
        features.update({
            "prev_word.lower()": prev_word.lower(),
            "prev_word.istitle()": prev_word.istitle(),
            "prev_word.isupper()": prev_word.isupper(),
        })
    else:
        features["BOS"] = True   # Beginning of sentence

    if i < len(sentence)-1:
        nxt_word = sentence[i+1]
        features.update({
            "next_word.lower()": nxt_word.lower(),
            "next_word.istitle()": nxt_word.istitle(),
            "next_word.isupper()": nxt_word.isupper(),
        })
    else:
        features["EOS"] = True   # End of sentence

    return features

#from datasets.iterable_dataset import Features
## Converting sentences into features

def sent2features(sentence):
  sentence_features = []
  for i in range(len(sentence)):
    sentence_features.append(features(sentence, i))
  return sentence_features

# Making the input_train features
X_train_feature = []
for sent in X_train:
  X_train_feature.append(sent2features(sent))

X_val_feature = []
for sent in X_val:
  X_val_feature.append(sent2features(sent))

print(X_val_feature[0])

X_test_feature = []
for sent in X_test:
  X_test_feature.append(sent2features(sent))



# Converting the Ner-tags into the actual word since crf can directly deal with the token without any encoding
label_names = train.features["ner_tags"].feature.names
y_train_updated = []
for sentence in y_train:
    y_train_updated.append([label_names[word] for word in sentence])


y_test_updated = []
for sentence in y_test:
    y_test_updated.append([label_names[word] for word in sentence])

#Applying Conditional Random Fields
import sklearn_crfsuite

crf = sklearn_crfsuite.CRF(
    algorithm="lbfgs",
    c1=0.1, #c1 = L1-Regularizer
    c2=0.1, #c2 = L2-Regularizer
    max_iterations=100,
    all_possible_transitions=True,
)

crf.fit(X_train_feature, y_train_updated)

from sklearn_crfsuite import metrics

y_pred = crf.predict(X_test_feature)

labels = sorted(crf.classes_)
labels.remove("O")

print(metrics.flat_classification_report(
    y_test_updated,
    y_pred,
    labels=labels,
    digits=4
))

"""**Finding the best hypermeters c1(L1 Regularizer) and c2(L2-Regularization) using the validation set**

"""

updated_y_val = [[label_names[t] for t in sent] for sent in y_val]

best_f1 = 0

for c1 in [0.01, 0.1]:
    for c2 in [0.01, 0.1]:
        crf = sklearn_crfsuite.CRF(
            algorithm="lbfgs",
            c1=c1,
            c2=c2,
            max_iterations=100,
            all_possible_transitions=True,
        )

        crf.fit(X_train_feature, y_train_updated)

        pred_y_val = crf.predict(X_val_feature)

        f1 = metrics.flat_f1_score(updated_y_val,pred_y_val, average="weighted")

        if f1 > best_f1:
            best_f1 = f1
            best_crf = crf

print("Best validation F1:", best_f1)

pred_y_test = best_crf.predict(X_test_feature)

crf.fit(X_train_feature, y_train_updated)

pred_y_test = crf.predict(X_val_feature)
print(metrics.flat_classification_report(updated_y_val, pred_y_val))

def print_top_5_state_features(crf):
    # top 5 state features
    state_feats = crf.state_features_

   
    top5 = sorted(state_feats.items(), key=lambda x: abs(x[1]), reverse=True)[:5]


    for (attr, label), weight in top5:
        # print(metrics.flat_classification_report(updated_y_val, pred_y_val))
        print(f"{weight:.4f}   {label:6}   {attr}")



print_top_5_state_features(best_crf)

