# -*- coding: utf-8 -*-
"""task_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b8JAia54P6uBiL_jS9DLUoed2BS_8TCY
"""

! gdown --id 194c49_ZKzw8onLA0qavaVpSn9DXBqBPx

!pip install scipy scikit-learn

import json
import numpy as np

from scipy.sparse import csr_matrix
from sklearn.decomposition import TruncatedSVD
from sklearn.preprocessing import normalize
from sklearn.metrics.pairwise import cosine_similarity

addr = "updated_vocab_document_dict.json"

with open(addr, "r", encoding="utf-8") as f:
    dataOfFile = json.load(f)

print("Total vocabulary words:", len(dataOfFile))

Task2_vocabulary = list(dataOfFile.keys())
word2idx = {word: idx for idx, word in enumerate(Task2_vocabulary)}
idx2word = {idx: word for word, idx in word2idx.items()}

V = len(Task2_vocabulary)
print("Vocabulary size (V):", V)

rows = []
cols = []
values = []

doc_id_map = {}
doc_counter = 0

for word in Task2_vocabulary:
    word_idx = word2idx[word]

    for entry in dataOfFile[word]:
        doc_id = entry[0]      # document id
        passage = entry[1]     # document text

        if doc_id not in doc_id_map:
            doc_id_map[doc_id] = doc_counter
            doc_counter += 1

        col_idx = doc_id_map[doc_id]

        tokens = passage.split()
        count = tokens.count(word)

        rows.append(word_idx)
        cols.append(col_idx)
        values.append(count)

D = doc_counter
print("Number of documents (D):", D)

X = csr_matrix((values, (rows, cols)), shape=(V, D))

print("Matrix shape (V x D):", X.shape)
print("Non-zero entries:", X.nnz)

def get_neighbors(embeddings, word, top_k=5):
    if word not in word2idx:
        return "Word not in vocabulary."

    idx = word2idx[word]
    # idx = word2idx[word]
    vector = embeddings[idx].reshape(1, -1)
    similarities = cosine_similarity(vector, embeddings)[0]
    #similarities = cosine_similarity(vector, embeddings)[0]
    indices = similarities.argsort()[-top_k-1:][::-1]

    results = []
    for counter in indices:
        if counter != idx:
            results.append((idx2word[counter], similarities[counter]))
            # idx = word2idx[word]

    return results[:top_k]
    #return results[-1::top_k-1]

d = 50
svd = TruncatedSVD(n_components=d, random_state=42)

embeddings_50 = svd.fit_transform(X)
#embeddings_50 = round(normalize(embeddings_50))
embeddings_50 = normalize(embeddings_50)


print("Embeddings shape:", embeddings_50.shape)

querywords = ["king", "month", "Arab"]

for searchword in querywords:
    print(f"\nTop neighbors for '{searchword}' (d=50):")
    print(get_neighbors(embeddings_50, searchword))

d = 100
svd = TruncatedSVD(n_components=d, random_state=42)
#querywords100 = ["Doha", "match", "win"]
embeddings_100 = svd.fit_transform(X)
#embeddings_100 = round(normalize(embeddings_100))
embeddings_100 = normalize(embeddings_100)

print("Embeddings shape:", embeddings_100.shape)

for kk in querywords:
    print(f"\nTop neighbors for '{kk}' (d=100):")
    print(get_neighbors(embeddings_100, kk))

d = 200
svd = TruncatedSVD(n_components=d, random_state=42)
#querywords200 = ["moment", "lose", "saudi","hero"]
embeddings_200 = svd.fit_transform(X)
#embeddings_200 = round(normalize(embeddings_200))
embeddings_200 = normalize(embeddings_200)

print("Embeddings shape:", embeddings_200.shape)

for word in querywords:
    print(f"\nTop neighbors for '{word}' (d=200):")
    print(get_neighbors(embeddings_200, word))

d = 300
svd = TruncatedSVD(n_components=d, random_state=42)
#querywords = ["oil", "huge", "rain","main","today"]
embeddings_300 = svd.fit_transform(X)
#embeddings_300 = round(normalize(embeddings_300))
embeddings_300 = normalize(embeddings_300)

print("Embeddings shape:", embeddings_300.shape)

for a in querywords:
    print(f"\nTop neighbors for '{a}' (d=300):")
    print(get_neighbors(embeddings_300, a))

