# -*- coding: utf-8 -*-
"""Task 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ujpvwZ9x4wS3Pcikw2xu8r-Mwbu0f0tA
"""

!gdown --id 194c49_ZKzw8onLA0qavaVpSn9DXBqBPx

!pip install scipy scikit-learn datasets==3.6.0 torch torchvision

import json
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim

import pandas as pd
import numpy as np

from scipy.sparse import csr_matrix
from sklearn.decomposition import TruncatedSVD
from sklearn.preprocessing import normalize
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics import accuracy_score, f1_score

addr = "updated_vocab_document_dict.json"

with open(addr, "r", encoding="utf-8") as f:
    dataOfFile = json.load(f)

print("Total vocabulary words:", len(dataOfFile))

Task2_vocabulary = list(dataOfFile.keys())
word_to_idx = {word: idx for idx, word in enumerate(Task2_vocabulary)}
idx_to_word = {idx: word for word, idx in word_to_idx.items()}

V = len(Task2_vocabulary)

rows = []
cols = []
values = []

doc_id_map = {}
doc_counter = 0

for word in Task2_vocabulary:
    word_idx = word_to_idx[word]

    for entry in dataOfFile[word]:
        doc_id = entry[0]
        passage = entry[1]

        if doc_id not in doc_id_map:
            doc_id_map[doc_id] = doc_counter
            doc_counter += 1

        col_idx = doc_id_map[doc_id]

        tokens = passage.split()
        count = tokens.count(word)

        rows.append(word_idx)
        cols.append(col_idx)
        values.append(count)

D = doc_counter
X_raw = csr_matrix((values, (rows, cols)), shape=(V, D))

print("Raw Matrix Shape:", X_raw.shape)

#Part 1 - TF-IDF Weighting


tfidf = TfidfTransformer(norm=None)
X_tfidf = tfidf.fit_transform(X_raw)

print("TF-IDF Matrix Shape:", X_tfidf.shape)

#Part 2 - SVD on RAW vs TF-IDF


best_d = 100
raw_svd = TruncatedSVD(n_components=best_d, random_state=42)
raw_emb= raw_svd.fit_transform(X_raw)
raw_emb = normalize(raw_emb)

tfidf_svd = TruncatedSVD(n_components=best_d, random_state=42)
tfidf_emb = tfidf_svd.fit_transform(X_tfidf)
tfidf_emb = normalize(tfidf_emb)

def neighbors(emb, word, top_k=5):
    if word not in word_to_idx:
        # idx = word_to_idx[word]
        # vector = emb[idx].reshape(1, -1)
        # similarities = cosine_similarity(vector, emb)[0]        
        return "Not there in Vocabulary"
        

    idx = word_to_idx[word]
    vector = emb[idx].reshape(1, -1)
    similarities = cosine_similarity(vector, emb)[0]

    indices = similarities.argsort()[-top_k-1:][::-1]

    results = []
    for loopcounter in indices:
        if loopcounter != idx:
            results.append((idx_to_word[loopcounter], similarities[loopcounter]))

    return results[:top_k]

#MLP with SVD TF-IDF vectors 

diverse_words = ["cup", "run", "India", "win", "yesterday"]
for word in diverse_words:
    # num_tags = len(tag_list)
    print(f"\nWORD: {word}")
    print("Raw SVD:", neighbors(raw_emb, word))
    print("TF-IDF SVD:", neighbors(tfidf_emb, word))

from datasets import load_dataset
dataset = load_dataset("conll2003")

def embedding(word):
    if word in word_to_idx:
        # print(f"\nWORD: {word}")
        return tfidf_emb[word_to_idx[word]]
    else:
        return np.zeros(best_d)

tag_list = dataset["train"].features["ner_tags"].feature.names
num_tags = len(tag_list)

def prepare_split(split):
    X_data = []
    y_data = []

    for example in dataset[split]:
        tokens = example["tokens"]
        tags = example["ner_tags"]

        for token, tag in zip(tokens, tags):
            X_data.append(embedding(token))
            y_data.append(tag)

    return torch.tensor(X_data, dtype=torch.float32), torch.tensor(y_data)

X_train, y_train = prepare_split("train")
X_test, y_test = prepare_split("test")

class MLP(nn.Module):
    def __init__(self, input_dim, num_classes):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(input_dim, 256),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(256, num_classes)
        )

    def forward(self, x):
        return self.model(x)

model = MLP(best_d, num_tags)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

epochs = 5

for epoch in range(epochs):
    model.train()
    optimizer.zero_grad()

    outputs = model(X_train)
    loss = criterion(outputs, y_train)

    loss.backward()
    optimizer.step()

    print(f"Epoch {epoch+1}, Loss: {loss.item()}")

"""## **Quality Check 2: Train final MLP using TF-IDF SVD vectors and report performance**"""

model.eval()
with torch.no_grad():
    outputs = model(X_test)
    predictions = torch.argmax(outputs, dim=1)

acc = accuracy_score(y_test.numpy(), predictions.numpy())
f1 = f1_score(y_test.numpy(), predictions.numpy(), average="macro")

print("Token Accuracy:", acc)
print("Macro F1:", f1)

