# -*- coding: utf-8 -*-
"""Glove pre-training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Q0O3BaflO_7hpgiylQwLPIbS46Khpzn
"""

! gdown --id 194c49_ZKzw8onLA0qavaVpSn9DXBqBPx

import numpy as np
import math
from collections import defaultdict
import json

import pandas as pd

addr = "updated_vocab_document_dict.json"

with open(addr, "r", encoding="utf-8") as f:
    FileData = json.load(f)

len(FileData)

doc_map = {}

for key in FileData:
    for doc_id, text in FileData[key]:
        doc_map[doc_id] = text

documents = list(doc_map.values())

print("Number of unique CC-News documents:", len(documents))

vocab = list(FileData.keys())
wordToid = {w: i for i, w in enumerate(vocab)}
idToWord = {i: w for w, i in wordToid.items()}
vocabbsize = len(vocab)

vocabbsize

import json

# Save vocab list to JSON
with open("vocab.json", "w") as f:
    json.dump(vocab, f, indent=4)

print("JSON file saved as vocab.json")

import re

WS = 5  # context window size

def preprocess(text):
    text = text.lower()
    text = re.sub(r"[^a-z0-9\s]", "", text)
    return text.split()


sample_tokens = []

for doc in documents[:5]:
    tokens = preprocess(doc)
    tokens = [t for t in tokens if t in wordToid]
    sample_tokens.append(tokens)

sample_tokens

from collections import defaultdict

X = defaultdict(float)

for doc in documents:
    tokens = preprocess(doc)
    tokens = [t for t in tokens if t in wordToid]

    for i in range(len(tokens)):
        wi = wordToid[tokens[i]]

        start = max(0, i - WS)
        end = min(len(tokens), i + WS + 1)

        for j in range(start, end):
            if i == j:
                continue

            wj = wordToid[tokens[j]]
            distance = abs(i - j)


            X[(wi, wj)] += 1.0 / distance

print("Number of co-occurrence pairs:", len(X))

WS = 5
embedding_dim = 200
x_max = 100
alpha = 0.75
learningRate = 0.005
epo = 15

for i in range(len(tokens)):
    target = wordToid[tokens[i]]

    start = max(0, i - WS)
    end = min(len(tokens), i + WS + 1)

    for j in range(start, end):
        if i != j:
            context = wordToid[tokens[j]]
            X[(target, context)] += 1

def weight(x):
    if x < x_max:
        return (x / x_max) ** alpha
    return 1

W = np.random.rand(vocabbsize, embedding_dim) * 0.01
C = np.random.rand(vocabbsize, embedding_dim) * 0.01

b = np.zeros(vocabbsize)
b_c = np.zeros(vocabbsize)

np.random.seed(42)

W = np.random.normal(0, 0.01, (vocabbsize, embedding_dim))
C = np.random.normal(0, 0.01, (vocabbsize, embedding_dim))

b = np.zeros(vocabbsize)
b_c = np.zeros(vocabbsize)

epo = 15
learningRate = 0.0005
MAXPAIRS = 1_000_000

X_items = list(X.items())[:MAXPAIRS]
print("Training on", len(X_items), "co-occurrence pairs")

for epoch in range(epo):
    total_loss = 0.0
    used = 0

    for (i, j), x in X_items:
        if x <= 0:
            continue

        w = weight(x)
        log_x = math.log(x + 1e-10)

        prediction = np.dot(W[i], C[j]) + b[i] + b_c[j]
        error = prediction - log_x

        if not np.isfinite(error):
            continue

        total_loss += w * error * error
        used += 1

        grad = w * error
        grad = max(min(grad, 5.0), -5.0)

        wi = W[i].copy()
        cj = C[j].copy()

        W[i] -= learningRate * grad * cj
        C[j] -= learningRate * grad * wi

        b[i] -= learningRate * grad
        b_c[j] -= learningRate * grad

    avg_loss = total_loss / max(used, 1)
    print(f"Epoch {epoch + 1} | Avg Loss = {avg_loss:.6f} | Used = {used}")

glove_embeddings_200 = W + C
glove_embeddings_200.shape

loss_history = {}
latency_history = {}

import time

glove_embeddings = {}
loss_history = {}
latency_history = {}

epo = 15
learningRate = 0.0005
MAXPAIRS = 1_000_000

X_items = list(X.items())[:MAXPAIRS]
print("Using", len(X_items), "co-occurrence pairs")

for d in [50, 100, 200, 300]:

    print(f"\nTraining GloVe with dimension d = {d}")

    epoch_losses = []
    start_time = time.time()

    np.random.seed(42)
    W = np.random.normal(0, 0.01, (vocabbsize, d))
    C = np.random.normal(0, 0.01, (vocabbsize, d))

    b = np.zeros(vocabbsize)
    b_c = np.zeros(vocabbsize)

    for epoch in range(epo):
        total_loss = 0.0
        used = 0

        for (indexi, indexj), x in X_items:

            if x <= 0:
                continue

            w_ij = weight(x)
            log_x = math.log(x + 1e-10)

            prediction = np.dot(W[indexi], C[indexj]) + b[indexi] + b_c[indexj]
            error = prediction - log_x

            if not np.isfinite(error):
                continue

            total_loss += w_ij * (error ** 2)
            used += 1

            grad = w_ij * error
            grad = np.clip(grad, -5.0, 5.0)

            wi = W[indexi].copy()
            cj = C[indexj].copy()

            W[indexi] -= learningRate * grad * cj
            C[indexj] -= learningRate * grad * wi
            # b = np.zeros(vocabbsize)
            # b_c = np.zeros(vocabbsize)
            b[indexi] -= learningRate * grad
            b_c[indexj] -= learningRate * grad

        avg_loss = total_loss / max(used, 1)
        epoch_losses.append(avg_loss)
        #This is inside loop training
        print(f"Epoch {epoch+1}/{epo} | Averaged Loss = {avg_loss:.6f}")


    glove_embeddings[d] = W + C

    loss_history[d] = epoch_losses

    latency_history[d] = time.time() - start_time

print("\nTraining Completed.")

import numpy as np
index_to_word = {}
for wIndex, idx in wordToid.items():
    index_to_word[idx] = wIndex

vecs = glove_embeddings[200]

def cosineSimilarity(v1, v2):
    num = np.dot(v1, v2)
    den = (np.linalg.norm(v1) * np.linalg.norm(v2)) + 1e-10
    return num / den

def GetTopNeighb(query_word, top_k=5):
    if query_word not in wordToid:
        # def cosineSimilarity(v1, v2):
        #   num = np.dot(v1, v2)
        #   den = (np.linalg.norm(v1) * np.linalg.norm(v2)) + 1e-10
        #   return num / den

        print(f"Word '{query_word}' not in vocabulary")
        return []

    Q_indx = wordToid[query_word]
    q_vec = vecs[Q_indx]

    Similarity_scores = []

    for index in range(vecs.shape[0]):
        if index == Q_indx:
            continue
        sim = cosineSimilarity(q_vec, vecs[index])
        Similarity_scores.append((index_to_word[index], sim))

    Similarity_scores.sort(key=lambda x: x[1], reverse=True)
    return Similarity_scores[:top_k]


queryWords = ["king", "month", "Arab","west","CSE728"]
#test_words2 = ["president","win","Rakesh"]

for word in queryWords:
    print(f"\nNearest neighbors of the ''{word}'':")
    neighbors = GetTopNeighb(word)
    for neigh, val in neighbors:
        print(f"  {neigh:<15} {val:.4f}")

import matplotlib.pyplot as plt

dimensions = [50, 100, 200, 300]
epochs = range(1, epo + 1)

plt.figure(figsize=(10,6))

for d in dimensions:
    plt.plot(epochs, loss_history[d], marker='o', label=f"d = {d}")

plt.xlabel("Epoch")
plt.ylabel("Average Loss")
plt.title("GloVe Loss Curves")
plt.legend()
plt.grid(True)
plt.show()

print("\nLatency Summary:")
for d in dimensions:
    print(f"d = {d} | Time = {latency_history[d]:.2f} seconds")