# -*- coding: utf-8 -*-
"""Task 4 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QEWY75LVWxiigXI7BAbA5u7dzpmO069i
"""

! gdown --id 194c49_ZKzw8onLA0qavaVpSn9DXBqBPx

!pip install scipy scikit-learn #installing scikit-learn for MLP

import numpy as np
import math
from collections import defaultdict
import json

addr = "updated_vocab_document_dict.json"

with open(addr, "r", encoding="utf-8") as f:
    dataOfFile = json.load(f)

vocabulary = set(dataOfFile.keys())
vocabulary = sorted(list(vocabulary))
vocabulary.append("UNK")
word2idx = {word: idx for idx, word in enumerate(vocabulary)}
idx2word = {idx: word for word, idx in word2idx.items()}
print(len(vocabulary))

V = len(vocabulary)

!pip install datasets==3.6.0

#Loading the dataset
from datasets import load_dataset
dataset = load_dataset("conll2003")

from datasets import concatenate_datasets
full_dataset = concatenate_datasets([
    dataset["train"],
    dataset["validation"],
    dataset["test"]
])

print(full_dataset[0])

"""GLOVE EMBEDDING"""

import numpy as np
from collections import defaultdict
from scipy.sparse import lil_matrix

window_size = 4

cooc = defaultdict(float)

for row in full_dataset:

    tokens = [t.strip().lower() for t in row["tokens"] if t.strip() != ""]

    for i, center in enumerate(tokens):

        if center not in word2idx:
            center = "UNK"

        center_id = word2idx[center]

        start = max(0, i - window_size)
        end = min(len(tokens), i + window_size + 1)

        for j in range(start, end):
            if i == j:
                continue

            context = tokens[j]
            if context not in word2idx:
                context = "UNK"

            context_id = word2idx[context]

            distance = abs(i - j)
            cooc[(center_id, context_id)] += 1.0 / distance

rows = []
cols = []
vals = []

for (i,j),v in cooc.items():
    rows.append(i)
    cols.append(j)
    vals.append(v)

from scipy.sparse import csr_matrix
X = csr_matrix((vals, (rows, cols)), shape=(V, V))

print("Co-occurrence matrix:", X.shape)

# Hyperparameters

epochs = 15
learningRate = 0.05
MAXPAIRS = 1_000_000
x_max = 100
alpha = 0.75
vocab_size = len(word2idx)

def weight(x):
    if x < x_max:
        return (x / x_max) ** alpha
    return 1.0

X_coo = X.tocoo()

X_items = list(zip(zip(X_coo.row, X_coo.col), X_coo.data))
# X_items = list(X.items())

if len(X_items) > MAXPAIRS:
    X_items = random.sample(X_items, MAXPAIRS)

print("Using", len(X_items), "co-occurrence pairs")

import numpy as np
import math
import random



glove_embeddings = {}

for d in [50, 100, 200, 300]:

    np.random.seed(42)

    W = np.random.randn(vocab_size, d) * 0.01
    C = np.random.randn(vocab_size, d) * 0.01

    b = np.zeros(vocab_size)
    b_c = np.zeros(vocab_size)

    for epoch in range(epochs):

        total_loss = 0
        used = 0

        random.shuffle(X_items)

        for (i, j), x in X_items:

            if x <= 0:
                continue

            w_ij = weight(x)
            log_x = math.log(x)

            pred = np.dot(W[i], C[j]) + b[i] + b_c[j]
            error = pred - log_x

            if not np.isfinite(error):
                continue

            grad = w_ij * error
            grad = np.clip(grad, -5.0, 5.0)

            wi = W[i].copy()
            cj = C[j].copy()

            W[i] -= learningRate * grad * cj
            C[j] -= learningRate * grad * wi

            b[i] -= learningRate * grad
            b_c[j] -= learningRate * grad

            total_loss += w_ij * error * error
            used += 1

        print(f"Epoch {epoch+1}/{epochs} | Avg Loss = {total_loss/max(used,1):.6f}")

    # Final word vectors = W + C
    emb = W + C

    # Normalize (important for cosine + MLP stability)
    norms = np.linalg.norm(emb, axis=1, keepdims=True) + 1e-8
    emb = emb / norms

    glove_embeddings[d] = emb

print("\nGloVe training complete.")

"""TRAINING GLOVE EMBEDDING"""

def build_training_data(embeddings, word2idx, full_dataset):

    X_train = []
    y_train = []

    unk_idx = word2idx["UNK"]

    for row in train:

        tokens = row["tokens"]
        ner_tags = row["ner_tags"]

        for tok, tag in zip(tokens, ner_tags):

            tok = tok.strip().lower()

            if tok in word2idx:
                vec = embeddings[word2idx[tok]]
            else:
                vec = embeddings[unk_idx]

            X_train.append(vec)
            y_train.append(tag)

    return np.array(X_train), np.array(y_train)

def build_test_data(embeddings, word2idx, test):

    X_test = []
    y_test = []

    unk_idx = word2idx["UNK"]

    for row in test:

        tokens = row["tokens"]
        ner_tags = row["ner_tags"]

        for tok, tag in zip(tokens, ner_tags):

            tok = tok.strip().lower()

            if tok in word2idx:
                vec = embeddings[word2idx[tok]]
            else:
                vec = embeddings[unk_idx]

            X_test.append(vec)
            y_test.append(tag)

    return np.array(X_test), np.array(y_test)

train = dataset["train"]
test = dataset["test"]
val = dataset["validation"]

from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report
import pickle

trained_models = {}
training_data = {}

dims = [50, 100, 200, 300]

for d in dims:


    X_train, y_train = build_training_data(
        glove_embeddings[d], word2idx, train
    )

    print("Training samples:", X_train.shape)

    mlp = MLPClassifier(
        hidden_layer_sizes=(256,),
        activation="relu",
        max_iter=20,
        random_state=42,
        verbose=True
    )

    mlp.fit(X_train, y_train)
    # store model + data
    trained_models[d] = mlp
    training_data[d] = (X_train, y_train)

#prediting on the test data
dim = [50,100,200,300]
for d in dim:
  X_test, y_test = build_test_data(glove_embeddings[d], word2idx, test)
  mlp = trained_models[d]
  preds = mlp.predict(X_test)
  print(f"The Classification report for {d} Dimensions")
  print(classification_report(y_test, preds))

from collections import defaultdict


rows = []
cols = []
vals = []

unk_idx = word2idx["UNK"]

for doc_id, row in enumerate(full_dataset):

    tokens = [t.strip().lower() for t in row["tokens"] if t.strip() != ""]

    # Count token frequencies in this sentence
    counts = defaultdict(int)

    for token in tokens:
        if token in word2idx:
            counts[token] += 1
        else:
            counts["UNK"] += 1   # OOV handling

    # Fill sparse matrix entries
    for word, count in counts.items():
        rows.append(word2idx[word])
        cols.append(doc_id)
        vals.append(count)


# Create CSR matrix
X = csr_matrix((vals, (rows, cols)), shape=(V, D))

print("CSR Matrix shape (V × D):", X.shape)
print("Number of non-zero entries:", X.nnz)

from sklearn.decomposition import TruncatedSVD
from sklearn.preprocessing import normalize

dims = [50, 100, 200, 300]
embeddings = {}

for d in dims:
    print(f"\nTraining SVD embeddings for d = {d}")

    svd = TruncatedSVD(n_components=d, random_state=42)
    emb = svd.fit_transform(X)     # (V × d)
    emb = normalize(emb)

    embeddings[d] = emb

    print("Embedding shape:", emb.shape)

import numpy as np

def build_training_data(embeddings, word2idx, full_dataset):

    X_train = []
    y_train = []

    unk_idx = word2idx["UNK"]

    for row in train:

        tokens = row["tokens"]
        ner_tags = row["ner_tags"]

        for tok, tag in zip(tokens, ner_tags):

            tok = tok.strip().lower()

            if tok in word2idx:
                vec = embeddings[word2idx[tok]]
            else:
                vec = embeddings[unk_idx]

            X_train.append(vec)
            y_train.append(tag)

    return np.array(X_train), np.array(y_train)

def build_test_data(embeddings, word2idx, test):

    X_test = []
    y_test = []

    unk_idx = word2idx["UNK"]

    for row in test:

        tokens = row["tokens"]
        ner_tags = row["ner_tags"]

        for tok, tag in zip(tokens, ner_tags):

            tok = tok.strip().lower()

            if tok in word2idx:
                vec = embeddings[word2idx[tok]]
            else:
                vec = embeddings[unk_idx]

            X_test.append(vec)
            y_test.append(tag)

    return np.array(X_test), np.array(y_test)

import numpy as np

def build_validation_data(embeddings, word2idx, val):

    X_val = []
    y_val = []

    unk_idx = word2idx["UNK"]

    for row in val:

        tokens = row["tokens"]
        ner_tags = row["ner_tags"]

        for tok, tag in zip(tokens, ner_tags):

            tok = tok.strip().lower()

            if tok in word2idx:
                vec = embeddings[word2idx[tok]]
            else:
                vec = embeddings[unk_idx]

            X_val.append(vec)
            y_val.append(tag)

    return np.array(X_val), np.array(y_val)

from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report
import pickle

trained_models = {}
training_data = {}

dims = [50,100, 200, 300]

for d in dims:

    print(f"\n=========== Training MLP (d={d}) ===========")

    X_train, y_train = build_training_data(
        embeddings[d], word2idx, train
    )

    print("Training samples:", X_train.shape)

    mlp = MLPClassifier(
        hidden_layer_sizes=(256,),
        activation="relu",
        max_iter=20,
        random_state=42,
        verbose=True
    )

    mlp.fit(X_train, y_train)

    # preds = mlp.predict(X_test)

    # print(classification_report(y_train, preds)) # printing the classification report of the training

    # store model + data
    trained_models[d] = mlp
    training_data[d] = (X_train, y_train)

#prediting on the test data
dim = [50,100,200,300]
for d in dim:
  X_test, y_test = build_test_data(embeddings[d], word2idx, test)
  mlp = trained_models[d]
  preds = mlp.predict(X_test)
  print(f"The Classification report for {d} Dimensions")
  print(classification_report(y_test, preds))

from sklearn.metrics import classification_report, f1_score

dims = [50, 100, 200, 300]

best_d = None
best_f1 = -1
best_preds = None
best_y = None

for d in dims:
    X_test, y_test = build_test_data(embeddings[d], word2idx, test)
    mlp = trained_models[d]
    preds = mlp.predict(X_test)

    # macro F1 (good for NER / multi-class imbalance)
    f1 = f1_score(y_test, preds, average="macro")

    print(f"Dimension {d} → Macro F1: {f1:.4f}")

    if f1 > best_f1:
        best_f1 = f1
        best_d = d
        best_preds = preds
        best_y = y_test

print(f"Best embedding dimension: {best_d}")
print(f"Best Macro F1: {best_f1:.4f}")

print(f"Final Classification Report for {best_d} Dimensions:")
print(classification_report(best_y, best_preds))

